owner: swipload
repo: status

sites:
  - name: Application
    url: $STATUS_APPURL
    maxResponseTime: 5000
  - name: API
    url: $STATUS_APIURL
    maxResponseTime: 5000
  - name: Integrations
    url: $STATUS_INTEGRATIONSURL
    maxResponseTime: 5000
    expectedStatusCodes:
      - 302
  - name: www.swipload.com
    url: https://www.swipload.com

status-website:
  cname: status.swipload.com
  # baseUrl: /status
  logoUrl: https://uploads-ssl.webflow.com/64b538b27cabeaaa12e11c6b/64e85127f7e60949397a3360_Webclip-2.png
  favicon: https://uploads-ssl.webflow.com/64b538b27cabeaaa12e11c6b/64e8511bb00b97ccab1cdff6_Favicon2.png
  name: Status
  introTitle: "**Swipload Services Status**"
  introMessage: Check the current Swipload health status and view past incidents.
  theme: light
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER

commitMessages:
  commitAuthorName: "Swip Bot"
  commitAuthorEmail: "status-bot@swipload.com"
